import streamlit as st

st.set_page_config(
    page_title="Sparrow Agent",
    page_icon="🪶",
    layout="wide"
)
with st.sidebar:

    st.title("🪶 Sparrow Agent")

    st.divider()

    st.header("Navigation")

    st.write("🏠 **Dashboard**")
    st.write("📄 **Resume Analysis**")
    st.write("📊 **Resume Score**")
    st.write("🎯 **ATS Score**")
    st.write("🧠 **Skill Gap**")
    st.write("💼 **Job Recommendations**")
    st.write("📥 **Download Report**")

    st.divider()

    st.caption("Version 0.3 - AI Resume Analysis Assistant")

from pypdf import PdfReader

from domain_detector import detect_domain

from career_analyzer import analyze_career

from resume_analyzer import analyze_resume

from report_generator import generate_report 

from utils import (
    get_today,
    get_candidate_name,
    get_rating,
)

from intelligence import analyze_candidate 

from career_coach import career_coach

from ai_chat import ask_ai

from career_profiles import CAREER_PROFILES

st.title("🪶 Sparrow Agent")

st.write("Welcome to Sparrow Agent!")

upload_file = st.file_uploader(
    "Upload a resume(PDF)", 
    type=["pdf"]
)

if upload_file is not None:
    st.success("Resume uploaded successfully!")

    pdf = PdfReader(upload_file)

    text = ""

    for page in pdf.pages:
        text += page.extract_text()

    st.session_state.resume_text = text    

    detected_domain, domain_scores, confidence = detect_domain(text)

    career_profile = CAREER_PROFILES.get(detected_domain)

    st.success(f"🎯 Detected Domain: {detected_domain}")

    st.caption(f"Confidence: {confidence}%")

    st.subheader("Extracted Resume Text")

    st.text_area(
        "Resume Content",
        text,
        height=300
    )
if "analyzed" not in st.session_state:
    st.session_state.analyzed = False

analyze = st.button("Analyze Resume")

if analyze:
    st.session_state.analyzed = True
    
text = st.session_state.get("resume_text", "")

strengths, weaknesses, suggestions = analyze_candidate(text)

if st.session_state.analyzed:
    resume_score, ats_score, career_score, missing_skills, skills_found = analyze_resume(
        text,
        detected_domain,
        career_profile
    )


    st.subheader("🧠 Sparrow Intelligence")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### 💪 Strengths")

        for strength in strengths:
            st.success(strength)

        st.markdown("### ⚠️ Weaknesses")

        for weakness in weaknesses:
            st.warning(weakness)

    with col2:
        st.markdown("### 💡 Suggestions")

        for suggestion in suggestions:
            st.info(suggestion)

    st.subheader("🎯 Career Match Dashboard")

    career_scores, best_role = analyze_career(text, detected_domain)

    career_score = career_scores[best_role]

    best_role = max(career_scores, key=career_scores.get)

    roles = career_profile["roles"].keys()

    cols = st.columns(2)

    for i, role in enumerate(roles):
        with cols[i % 2]:
            with st.container(border=True):
                st.markdown(f"### 💼 {role}")
                st.metric("Match", f"{career_scores[role]}%")
                st.progress(career_scores[role] / 100)

    st.divider()

    advice = career_coach(text)

    st.subheader("🪶 Why This Career Matches You")   

    with st.container(border=True):
        st.markdown("## 🎯 Best Career Match")
        st.metric(
            "Recommended Role",
            best_role
        )
        
    aliases = {
        "AUTOCAD": [
            "AUTOCAD",
            "AUTO CAD",
            "AUTO-CAD",
            "AUTODESK AUTOCAD"
        ],

        "STAAD": [
            "STAAD",
            "STAAD PRO",
            "STAAD-PRO",
            "STAADPRO",
            "STAAD.PRO"
        ]
    }

    for skill in career_profile["required_skills"]:

        keywords = aliases.get(skill, [skill])

        if any(keyword in text.upper() for keyword in keywords):
            st.write(f"✅ {skill} detected")

        else:
            st.write(f"❌ {skill} not detected")


    st.info(f"""
    Sparrow selected **{best_role}** because your resume demonstrates strong technical skills and is the best overall match based on the detected technologies in your resume.
    """)

        
    candidate = get_candidate_name(text)

    rating = get_rating(career_score)
    
    report = generate_report(
        candidate,
        ats_score,
        career_score,
        best_role,
        rating,
        skills_found
    )
    
    
    st.download_button(
        label="📄 Download Report",
        data=report,
        file_name="sparrow_report.txt",
        mime="text/plain"
        )

    if st.button(
        "✨ Analyze with Sparrow AI",
        use_container_width=True
    ):

            prompt = f"""
            You are Sparrow AI Career Mentor.

            The user's selected career domain is:

            {detected_domain}

            The following report was generated by Sparrow Agent after resume analysis,
            ATS evaluation, career matching and career coaching.

            Treat the report as factual.

            Do NOT change the analysis.

            Do NOT contradict the report.

            Instead, explain it professionally while tailoring all advice specifically for the user's career domain.

            For example:

            - If the domain is AI & Data Science, recommend AI technologies and career paths.
            - If the domain is Software Engineering, recommend software engineering technologies and roles.
            - If the domain is Mechanical Engineering, recommend mechanical engineering skills and careers.
            - If the domain is Civil Engineering, recommend civil engineering skills and careers.
            - If the domain is Business & Management, recommend business-related careers and certifications.

            Sparrow Career Report:

            {report}

            Respond in Markdown.

            Use these sections:

            # 📌 Career Summary

            # 💪 Key Strengths

            # ⚠ Areas for Improvement

            # 📚 Recommended Learning Path

            # 🚀 Next Career Steps

            # ⭐ Final Advice

            Keep the response under 300 words.

            Be encouraging, realistic and actionable.
            """

            with st.spinner("🪶 Sparrow AI is analyzing your report... Please wait..."):
                response = ask_ai(prompt)

            st.toast("🪶 Sparrow AI analysis completed!")  

            st.divider()

            st.subheader("🪶 Sparrow AI Career Mentor")
            st.caption("Powered by Google Gemini 2.5 Flash AI")

            with st.container(border=True):
                st.markdown(response)