def generate_report(
    candidate,
    ats_score,
    career_score,
    best_role,
    rating,
    skills
):

    report = f"""
============================================================
🪶                 SPARROW AGENT REPORT
============================================================

Candidate Name : {candidate}

Overall Rating : {rating}

Recommended Career :
{best_role}

------------------------------------------------------------
📊 SCORES
------------------------------------------------------------

ATS Score           : {ats_score}/100
Career Readiness    : {career_score}/100

------------------------------------------------------------
🛠️ DETECTED SKILLS
------------------------------------------------------------

{", ".join(skills)}

------------------------------------------------------------
💡 SPARROW'S ASSESSMENT
------------------------------------------------------------

Your resume demonstrates a solid technical foundation.
Based on the technologies and experience detected,
Sparrow recommends pursuing the role of:

⭐ {best_role}

Continue strengthening your portfolio with practical
projects, internships, certifications and consistent
learning to improve your employability.

============================================================
Generated by Sparrow Agent
AI Resume Analysis Assistant
============================================================
"""

    return report